### PR TITLE
Explore streaming LMNT speech with chat text.

### PR DESCRIPTION
**Pull request by shaper**
Built against 'lmnt-node' ToT at https://github.com/lmnt-com/lmnt-node and 'ai' ToT at https://github.com/vercel/ai/.

Notes:
- only server-side implemented currently
- possible 'lmnt-node' bug - the for-await loop in 'audioReadTask' seems to never exit on 'await'

### CODE REVIEW

**Comment by shaper** [comment]
Install steps for iteration:

- clone https://github.com/lmnt-com/lmnt-node
- `cd` into `lmnt-node` and run `pnpm install && pnpm link --global`
- clone https://github.com/vercel/ai/
- `cd` into `ai` and run `pnpm install && link --global`
- clone this repo, patch this PR, `cd` into `ai-chatbot`
- `pnpm link --global ai`
- `pnpm link --global lmnt-node`
- `pnpm install`
- place the appropriate user-specific configuration in `.env`
- `pnpm dev`

**Comment by shaper** [comment]
> @shaper is attempting to deploy a commit to the **Vercel** Team on [Vercel](https://vercel.com).
> 
> A member of the Team first needs to [authorize it](https://vercel.com/git/authorize?team=Vercel&type=github&job=%7B%22headInfo%22%3A%7B%22sha%22%3A%22fac944fded42439e5af103df00c1ec4cd26d48b3%22%7D%2C%22id%22%3A%22QmWv92uXxsaXTwG78F9LbfwY4pGpBvsfyVi3NAoVgLeazq%22%2C%22org%22%3A%22vercel-labs%22%2C%22prId%22%3A151%2C%22repo%22%3A%22ai-chatbot%22%7D).

Sorry folks, I intended to push this as a WIP PR alongside our fork as incremental progress for an exploration. I missed altering the target branch.

I'll leave this for the time being but we are not looking to merge it to your repo currently, happy to close and work separately as desired.

**Comment by shaper** [comment]
> * possible 'lmnt-node' bug - the for-await loop in 'audioReadTask' seems to never exit on 'await'

https://github.com/lmnt-com/lmnt-node/pull/11 fixes this.

**Comment by leerob** [comment]
Really neat! Thanks for sharing. We aren't going to merge this back in, but appreciate the PR.

**Pull request closed without merging**
