### PR TITLE
Feature/model selector

### PR DESCRIPTION
**Pull request by CarlosZiegler**
After sync my fork its closed my PR, now created a new branch. 
- Update branch form main and requested adjust from PR #32 

* Small adjust on small screens ( user name )
image

* adjust conditional for empty page.
* add alert if not logged ing if tried to send chat 
image

* add model selector into action button 
image

image

### CODE REVIEW

**Comment by jaredpalmer** [comment]
We decided internally that we want to keep the project as a starter kit and will not be adding advanced features like model selection. The other changes can be accepted.

**Comment by CarlosZiegler** [comment]
What changes was accepted?

**Comment by swyxio** [comment]
i have implemented for now, thank you @CarlosZiegler https://smoltalk.vercel.app/

**Comment by CarlosZiegler** [comment]
@swyxio looks good :)

**Pull request closed without merging**
